export const assets = {
    water_tileset:"/assets/phaser/water-map/water_tileset.png",
    thunder_tileset:"/assets/phaser/thunder-map/thunder_tileset.png",
    fire_tileset:"/assets/phaser/fire-map/fire_tileset.png",
    central_tileset:"/assets/phaser/central-map/central_tileset.png",
    water_tilemap:"/assets/phaser/water-map/water-map.json",
    thunder_tilemap:"/assets/phaser/thunder-map/thunder-map.json",
    fire_tilemap:"/assets/phaser/fire-map/fire-map.json",
    central_tilemap:"/assets/phaser/central-map/central-map.json",
    over_the_player_layer:"/assets/phaser/central-map/AbovePlayerTiles.png",
    player_sprite:"/assets/phaser/dude.png",
    lootbox_closed:"/assets/phaser/lootbox-closed.png",
    lootbox_open:"/assets/phaser/lootbox-open.png",
    arena:"/assets/phaser/arena.webp",
    teleporter:"/assets/phaser/pikachu.png",
}